/* Generated by AN DISI Unibo */ 
package it.unibo.perimeter

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.*

class Perimeter ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		val vr = VrobotLLMoves24.create("localhost",myself)
		 var stepr = false  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name: starting...")
						
									vr.setTrace(true)
									vr.halt() //per sbloccare eventuali notallowed
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="turnleftandgo", cond=doswitch() )
				}	 
				state("turnleftandgo") { //this:State
					action { //it:State
						 vr.turnLeft()  
						CommUtils.outmagenta("$name: turn left and go!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveforward", cond=doswitch() )
				}	 
				state("moveforward") { //this:State
					action { //it:State
						 stepr = vr.step(300)  
						CommUtils.outmagenta("$name: step(300)")
						if(  stepr == true  
						 ){forward("stepdone", "stepdone(1)" ,name ) 
						}
						else
						 {forward("stepfailed", "stepfailed(1)" ,name ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="moveforward",cond=whenDispatch("stepdone"))
					transition(edgeName="t01",targetState="turnright",cond=whenDispatch("stepfailed"))
					transition(edgeName="t02",targetState="handlesonar",cond=whenEvent("sonardata"))
				}	 
				state("turnright") { //this:State
					action { //it:State
						 vr.turnRight()  
						CommUtils.outmagenta("$name: turn right")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveforward", cond=doswitch() )
				}	 
				state("handlesonar") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name: stopped and ignoring all messages from sonar for 2 sec")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handlesonar", 
				 	 					  scope, context!!, "local_tout_"+name+"_handlesonar", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="resume",cond=whenTimeout("local_tout_"+name+"_handlesonar"))   
				}	 
				state("resume") { //this:State
					action { //it:State
						CommUtils.outblack("$name: resume movement")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="moveforward",cond=whenDispatch("stepdone"))
					transition(edgeName="t05",targetState="turnright",cond=whenDispatch("stepfailed"))
				}	 
			}
		}
} 
